#!/bin/bash
timedatectl set-ntp true
fdisk -l
echo "Which partition would you like to install to?"
read partition
mkfs.btrfs -f $partition
mount $partition /mnt
echo "Installing programs..."
pacstrap /mnt base linux linux-firmware 
genfstab -U /mnt >> /mnt/etc/fstab
cp arch-install-2 /mnt/
arch-chroot /mnt ./arch-install-2 chroot
#this runs after second file completes
echo "chrooting into system now."
arch-chroot /mnt
