#!/bin/bash
ln -sf /usr/share/zoneinfo/America/Los_Angeles /etc/localtime
hwclock --systohc
#uncomment "en_US.UTF-8 UTF-8" in /etc/locale.gen
sed -i -e 's/#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/g' /etc/locale.gen
locale-gen
echo "LANG=en_US.UTF-8" >> /etc/locale.conf
echo "Input hostname:"
read hostname
echo $hostname >> /etc/hostname
echo -e 127.0.0.1	localhost::1		localhost127.0.1.1	$hostname.localdomain	$hostname >> /etc/hosts
sed -i -e 's/#Color/Color/g' /etc/pacman.conf
echo "Please set root password"
passwd
echo "Input username (no caps):"
read username
#User input
useradd -m $username
echo "Please set user password"
passwd $username
#echo "Giving user root priveleges..."
#Do with visudo? currently breaks sudo
sed -i s/'root   ALL=(ALL) ALL'/'root   ALL=(ALL) ALL\n'$username'   ALL=(ALL) ALL'/ /etc/sudoers
#echo $username" ALL=(ALL) ALL" >> /etc/sudoers
echo "Installing additional packages..."
pacman --noconfirm -Syu tmux vim networkmanager man-db man-pages texinfo btrfs-progs plasma-meta breeze-gtk kdeconnect ntfs-3g openssh sudo zsh git base-devel plasma-wayland-session neofetch signal-desktop vlc yakuake htop calibre libreoffice-fresh reflector bat firefox xfce4-terminal
echo "Installing paru..."
cd /home/$username
git clone https://aur.archlinux.org/paru.git
chown $username:$username paru/ -R
cd paru
#-u $username avoids makepkg erroring when run as root
sudo -u $username makepkg -si --noconfirm
cd
#Remove install folder
rm -rf paru/
echo "Setting shell to zsh..."
chsh -s /usr/bin/zsh $username                                                                                                                                                                                                   
chsh -s /usr/bin/zsh
#This echo is ugly, but without it the zsh automatic setup launches
echo -e "# The following lines were added by compinstall\n\nzstyle ':completion:*' completer _complete _ignored _correct _approximate\nzstyle ':completion:*' matcher-list 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' ''\nzstyle :compinstall filename '/home/prasiddh/.zshrc'\n\nautoload -Uz compinit\ncompinit\n# End of lines added by compinstall\n# Lines configured by zsh-newuser-install\nHISTFILE=~/.histfile\nHISTSIZE=1000\nSAVEHIST=5000\nunsetopt beep\nbindkey -v\n# End of lines configured by zsh-newuser-install" >> /home/$username/.zshrc
echo "Install AUR packages? This will take a while. [y/n]"
read choice
if [[ $choice == y* ]]; then
    #currently broken, need to find out how to run it as a different user
    echo "Installing AUR packages..."
    sudo -u $username paru --noconfirm -S starship-bin nerd-fonts-complete intellij-idea-ultimate-edition-jre
    echo "Setting zsh theme... "
    echo 'eval "$(starship init zsh)"' >> .zshrc
    exit
else
    echo "Skipping AUR packages..."
fi
echo "Adding aliases..."
#yay is the superior name
echo alias yay='paru'>>/home/$username/.zshrc
echo alias yay='paru'>>/home/$username/.bashrc
#make sudo work with aliases & refresh timeout
echo alias sudo='sudo -v; sudo '>>/home/$username/.zshrc
echo alias sudo='sudo -v; sudo '>>/home/$username/.bashrc
#command confirmation
echo alias rm='rm -i'>>/home/$username/.zshrc
echo alias rm='rm -i'>>/home/$username/.bashrc
echo alias mv='mv -i'>>/home/$username/.zshrc
echo alias mv='mv -i'>>/home/$username/.bashrc
echo alias cp='cp -i'>>/home/$username/.zshrc
echo alias cp='cp -i'>>/home/$username/.bashrc
#speed up commands
echo alias mnt='mount'>>/home/$username/.zshrc
echo alias mnt='mount'>>/home/$username/.bashrc
echo alias clr='clear'>>/home/$username/.zshrc
echo alias clr='clear'>>/home/$username/.bashrc

#This shouldn't be necessary anymore
#echo "Enabling services..."
#systemctl enable NetworkManager.service
#systemctl enable sddm.service
echo "Done! Make sure to install a bootloader and intel/amducode depending on your system."
