#!/bin/bash
ln -sf /usr/share/zoneinfo/America/Los_Angeles /etc/localtime
hwclock --systohc
#find a way to uncomment "en_US.UTF-8 UTF-8" in /etc/locale.gen
sed -i -e 's/#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/g' /etc/locale.gen
locale-gen
echo "LANG=en_US.UTF-8" >> /etc/locale.conf
echo Input hostname:
read hostname
echo $hostname >> /etc/hostname
echo -e 127.0.0.1	localhost::1		localhost127.0.1.1	$hostname.localdomain	$hostname >> /etc/hosts
sed -i -e 's/#Color/Color/g' /etc/pacman.conf
echo Installing yay...
git clone https://github.com/Jguer/yay
cd yay
sudo -u nobody makepkg -si
cd
echo "Please set root password"
passwd
echo Input username:
read username
useradd -m $username
echo "Please set user password"
passwd $username
